<?php include "Partials/header.php"; ?>
<?php include "Partials/loggedInNav.php"; ?>

<div class="row"> 

    <div class="col-md-12 text-center datePickerControls">
        <a class="btn btn-default btn-lg" 
        href="/reservations/<?php echo $previousDay ?>">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        </a> 
        
        <input data-toggle="datepicker" id="datepicker" class="btn btn-default btn-lg">
        
        <a class="btn btn-default btn-lg" href="/reservations/<?php echo $nextDay ?>">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        </a>
    </div>
</div>


<div class="row">
    <div class="col-md-12">
        <div class="table-responsive">

            <table class="table table-bordered">

                <!-- Table head -->
                <!-- - row consists of text 'heure' + one cell per salle, generated by iterating over $salleList -->
                <thead>
                    <tr class="info">
                        <th class="hoursHeading">heure</th>
                        <?php foreach($salleList as $salle):?>
                            <th class="text-center">
                                <?php echo $salle['name']?>
                            </th>
                        <?php endforeach; ?>
                    </tr>
                </thead>

                <!-- Table body -->
                <!-- row consists of $hour + one cell per $reservation, generated by iterating over $reservationListByHour --> 
                <tbody>
                    <?php foreach($reservationListByHour as $hour => $reservationList): ?>

                        <tr>
                            <td>
                                <span class="hours"><?php echo date("H:i", strtotime($hour));; ?></span>
                            </td>

                            <!-- Iterate over each reservation -->
                            <!-- index is used to keep track of the corresponding salle -->
                            <?php 
                                $index = 0;
                                foreach($reservationList as $reservation): 
                                    $currentSalle = $salleList[$index];
                                    $index++;
                            ?>

                                <!-- if the reservation exists and it was created by the current user, link to modify Reservation modal -->
                                <?php if (isset($reservation['id']) && $reservation['userId'] === $userId) { ?>
                                <td class="success text-center">
                                    <!-- data-toggle and data-target are used to initialize the bootstrap modal -->
                                    <!-- the other data-* attributes are used to transmit data to the modal via jquery (see script below) -->
                                    <a href="#" 
                                        data-toggle="modal" 
                                        data-target="#updateReservationModal"
                                        data-currenthour="<?php echo $hour;?>"
                                        data-currentsalleid="<?php echo $currentSalle['id'];?>"
                                        data-day="<?php echo $day;?>"
                                        data-userid="<?php echo $userId;?>"
                                        data-numguests="<?php echo $reservation['numGuests'];?>"
                                        data-reservationid="<?php echo $reservation['id'];?>"
                                        data-title="<?php echo $reservation['title'];?>"
                                    >
                                        <?php echo $reservation['title'] ?>
                                    </a>
                                </td>

                                <!-- if the reservation exists but it wasn't created by the current user, modal to alert the user -->
                                <?php } else if (isset($reservation['id']) && $reservation['userId'] !== $userId) { ?>
                                <td class="warning text-center">
                                    <!-- data-toggle and data-target are used to initialize the bootstrap modal -->
                                    <a href="#" 
                                        data-toggle="modal" 
                                        data-target="#alertNotCorrectUserModal"
                                    >
                                        <?php echo $reservation['title'] ?>
                                    </a>
                                </td>

                                <!-- if the reservation doesn't exist, link to update Reservation modal -->
                                <?php } else { ?>

                                <td class="text-center">
                                    <!-- data-toggle and data-target are used to initialize the bootstrap modal -->
                                    <!-- the other data-* attributes are used to transmit data to the modal via jquery (see script below) -->
                                    <a href="#" 
                                        data-toggle="modal" 
                                        data-target="#createReservationModal"
                                        data-currenthour="<?php echo $hour;?>"
                                        data-currentsalleid="<?php echo $currentSalle['id'];?>"
                                        data-day="<?php echo $day;?>"
                                        data-userid="<?php echo $userId;?>"
                                    >
                                        <span class="hiddenLink">link</span>
                                    </a>
                                </td>
                                <?php }?>


                            <?php endforeach ?>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>

        </div>
    </div>
</div>

<!-- Alert when the user tries to modify another user's reservation modal -->
<div class="modal fade" id="alertNotCorrectUserModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal header -->
            <div class="modal-body">
                <button type="button" class="close" data-dismiss="modal">
                    <span>&times;</span>
                    <span class="sr-only">Close</span>
                </button>
                <p>
                    Vous ne pouvez pas modifer les réservations des autres utilisateurs
                </p>
            </div>
        </div>
    </div>
</div>


<!-- Create reservation modal -->
<div class="modal fade" id="createReservationModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal header -->
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span>&times;</span>
                    <span class="sr-only">Close</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">
                    Créer une réservation
                </h4>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <form action="/reservation/create" method="post" id="createReservationForm">

                    <div class="form-group">
                        <label for="title">Titre</label>
                        <input type="text" name="title" id="title" value="Exemple de titre" class="form-control" required>
                    </div>

                    <div class="form-group">
                        <label for="salleId">Salle</label>
                        <select name="salleId" id="salleId" class="form-control">
                            <!-- php is used to display the list of all possible values -->
                            <!-- jquery (see script below) is used to select a default vaue -->
                            <?php foreach($salleList as $salle): ?>
                                <option value="<?php echo $salle['id'] ?>" >
                                    <?php echo $salle['name'] ?>
                                </option>
                            <?php endforeach ?>
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="hourId">Heure</label>
                        <select name="hourId" id="hourId" class="form-control">
                            <!-- php is used to display the list of all possible values -->
                            <!-- jquery (see script below) is used to select a default vaue -->
                            <?php foreach($possibleHoursList as $hour): ?>
                                <option value="<?php echo $hour['id'] ?>">
                                    <?php echo $hour['hour'] ?>
                                </option>
                            <?php endforeach ?>
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="numGuests">Nombre de personnes</label>
                        <input type="number" name="numGuests" id="numGuests" value="10" class="form-control" min="1" required>
                    </div>

                    <div class="form-group">
                        <label for="day">Jour</label>
                        <input type="text" name="day" id="day" class="form-control" required>
                    </div>

                    <input type="hidden" name="userId" id="userId">

                    <button type="submit" class="btn btn-primary">Créer la réservation</button>

                </form>
            </div>
        </div>
    </div>
</div>


<!-- Update reservation modal -->
<div class="modal fade" id="updateReservationModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal header -->
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span>&times;</span>
                    <span class="sr-only">Close</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">
                    Modifier une réservation
                </h4>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <form method="post" id="updateReservationForm">

                    <div class="form-group">
                        <label for="title">Titre</label>
                        <input type="text" name="title" id="title" class="form-control" required>
                    </div>

                    <div class="form-group">
                        <label for="salleId">Salle</label>
                        <select name="salleId" id="salleId" class="form-control">
                            <!-- php is used to display the list of all possible values -->
                            <!-- jquery (see script below) is used to select a default vaue -->
                            <?php foreach($salleList as $salle): ?>
                                <option value="<?php echo $salle['id'] ?>" >
                                    <?php echo $salle['name'] ?>
                                </option>
                            <?php endforeach ?>
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="hourId">Heure</label>
                        <select name="hourId" id="hourId" class="form-control">
                            <!-- php is used to display the list of all possible values -->
                            <!-- jquery (see script below) is used to select a default vaue -->
                            <?php foreach($possibleHoursList as $hour): ?>
                                <option value="<?php echo $hour['id'] ?>">
                                    <?php echo $hour['hour'] ?>
                                </option>
                            <?php endforeach ?>
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="numGuests">Nombre de personnes</label>
                        <input type="number" name="numGuests" id="numGuests" class="form-control" min="1" required>
                    </div>

                    <div class="form-group">
                        <label for="day">Jour</label>
                        <input type="text" name="day" id="day" class="form-control" required>
                    </div>

                    <input type="hidden" name="userId" id="userId">

                    <button type="submit" class="btn btn-primary">Modifier la réservation</button>

                </form>

                <form method="post" id="deleteReservationForm">

                    <input type="hidden" name="userId" id="userId">

                    <button type="submit" class="btn btn-default">Supprimer la réservation</button>

                </form>

            </div>
        </div>
    </div>
</div>



<!-- dynamic modal script -->
<script type="text/javascript">

    $('#createReservationModal').on('show.bs.modal', function (event) {
        var link = $(event.relatedTarget); // Button that triggered the modal

        // Extract info from data-* attributes
        var currentHour = link.data('currenthour'); 
        var currentSalleId = link.data('currentsalleid');
        var day = link.data('day'); 
        var userId = link.data('userid') ;

        var modal = $(this);

        modal.find("#hourId option").filter(function() {
            return this.text == currentHour; 
        }).attr('selected', true);

        modal.find('#salleId').val(currentSalleId);
        modal.find('#day').val(day);
        modal.find('#userId').val(userId);

        console.log(currentHour);
        console.log(currentSalleId);
        console.log(day);
        console.log(userId);
    })


    $('#updateReservationModal').on('show.bs.modal', function (event) {
        var link = $(event.relatedTarget); // Button that triggered the modal

        // Extract info from data-* attributes
        var currentHour = link.data('currenthour');
        var currentSalleId = link.data('currentsalleid');
        var day = link.data('day');
        var userId = link.data('userid'); 
        var title = link.data('title');
        var reservationId = link.data('reservationid');
        var numGuests = link.data('numguests');

        var modal = $(this);

        modal.find("#hourId option").filter(function() {
            return this.text == currentHour; 
        }).attr('selected', true);

        modal.find('#salleId').val(currentSalleId);
        modal.find('#day').val(day);
        modal.find('#userId').val(userId);
        modal.find('#title').val(title);
        modal.find('#numGuests').val(numGuests);

        modal.find("#updateReservationForm").attr("action", "/reservation/update/" + reservationId);
        modal.find("#deleteReservationForm").attr("action", "/reservation/delete/" + reservationId);


        console.log(currentHour);
        console.log(currentSalleId);
        console.log(day);
        console.log(userId);
        console.log(title);
        console.log(reservationId);
        console.log(numGuests);
    });



</script>



<!-- datepicker script -->
<script type="text/javascript">

    $('[data-toggle="datepicker"]').datepicker({
        autoPick: 'true',
        format: 'yyyy-mm-dd',
        date: '<?php echo $day ?>',
        weekStart: '1',
        filter: function(date) {
            if (date.getDay() === 0 || date.getDay() === 6) {
                return false; // Disable all Sundays and Saturdays
            }
        }
    });
    
    $("#datepicker").change(function() {
        var day = $('#datepicker').val();
        window.location.href = "/reservations/" + day;
    });

</script>

<!-- table hover script -->
<script type="text/javascript">

    $(document).ready(function(){
        $('table tbody tr td').on('hover', function () {
            $(this).toggleClass('hoverCell');
        });
    });

</script>


<?php include "Partials/footer.php"; ?>

